name: Build Cling for Termux (aarch64)

on:
  workflow_dispatch:
  push:
    paths:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_NDK_VERSION: r29
      API_LEVEL: 24
      ARCH: arm64
      TARGET: aarch64-linux-android

    steps:
      - name: Checkout LLVM
        uses: actions/checkout@v4
        with:
          repository: root-project/llvm-project
          path: llvm
          ref: cling-latest
          fetch-depth: 1

      - name: Checkout Cling
        uses: actions/checkout@v4
        with:
          repository: root-project/cling
          path: cling
          fetch-depth: 1

      - name: Setup NDK Clang
        uses: Ylarod/setup-ndk-clang@v1.0.0
        with:
            ndk-version: ${{ env.ANDROID_NDK_VERSION }}


      - name: Prepare build directory
        run: |
          mkdir build

      - name: Configure for Termux (ARM64)
        working-directory: build
        run: |
          cmake -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=$PWD/install \
            -DCMAKE_SYSTEM_NAME=Android \
            -DCMAKE_SYSTEM_VERSION=24 \
            -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
            -DCMAKE_ANDROID_NDK=$ANDROID_NDK_HOME \
            -DCMAKE_C_COMPILER=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang \
            -DCMAKE_CXX_COMPILER=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang++ \
            -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
            -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
            -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY \
            -DLLVM_EXTERNAL_PROJECTS=cling \
            -DLLVM_EXTERNAL_CLING_SOURCE_DIR=../cling/ \
            -DLLVM_ENABLE_PROJECTS="clang" \
            -DLLVM_TARGETS_TO_BUILD="AArch64" \
            -DLLVM_DEFAULT_TARGET_TRIPLE=aarch64-linux-android \
            -DLLVM_HOST_TRIPLE=aarch64-linux-android \
            -DLLVM_TARGET_ARCH=AArch64 \
            -DLLVM_TABLEGEN=$PWD/../native-build/bin/llvm-tblgen \
            -DCLANG_TABLEGEN=$PWD/../native-build/bin/clang-tblgen \
            -DLLVM_BUILD_RUNTIME=OFF \
            -DLLVM_INCLUDE_TESTS=OFF \
            -DLLVM_INCLUDE_EXAMPLES=OFF \
            -DLLVM_INCLUDE_BENCHMARKS=OFF \
            -DLLVM_ENABLE_TERMINFO=OFF \
            -DLLVM_ENABLE_LIBEDIT=OFF \
            -DLLVM_ENABLE_ZLIB=OFF \
            -DLLVM_ENABLE_LIBXML2=OFF \
            -DLLVM_TARGETS_TO_BUILD="host;NVPTX" \
            ../llvm/llvm/

      - name: Build native tools first (for tablegen)
        run: |
          mkdir native-build
          cd native-build
          cmake -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_PROJECTS="clang" \
            -DLLVM_TARGETS_TO_BUILD="AArch64" \
            ../llvm/llvm/
          ninja llvm-tblgen clang-tblgen

      - name: Reconfigure with native tablegen
        working-directory: build
        run: |
          cmake -G Ninja \
            -DCMAKE_BUILD_TYPE=MinSizeRel \
            -DCMAKE_INSTALL_PREFIX=$PWD/install \
            -DCMAKE_SYSTEM_NAME=Android \
            -DCMAKE_SYSTEM_VERSION=24 \
            -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
            -DCMAKE_ANDROID_NDK=$ANDROID_NDK_HOME \
            -DCMAKE_C_COMPILER=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang \
            -DCMAKE_CXX_COMPILER=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang++ \
            -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
            -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
            -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY \
            -DLLVM_EXTERNAL_PROJECTS=cling \
            -DLLVM_EXTERNAL_CLING_SOURCE_DIR=../cling/ \
            -DLLVM_ENABLE_PROJECTS="clang" \
            -DLLVM_TARGETS_TO_BUILD="AArch64" \
            -DLLVM_DEFAULT_TARGET_TRIPLE=aarch64-linux-android \
            -DLLVM_HOST_TRIPLE=aarch64-linux-android \
            -DLLVM_TARGET_ARCH=AArch64 \
            -DLLVM_TABLEGEN=$PWD/../native-build/bin/llvm-tblgen \
            -DCLANG_TABLEGEN=$PWD/../native-build/bin/clang-tblgen \
            -DLLVM_BUILD_RUNTIME=OFF \
            -DLLVM_INCLUDE_TESTS=OFF \
            -DLLVM_INCLUDE_EXAMPLES=OFF \
            -DLLVM_INCLUDE_BENCHMARKS=OFF \
            -DLLVM_ENABLE_TERMINFO=OFF \
            -DLLVM_ENABLE_LIBEDIT=OFF \
            -DLLVM_ENABLE_ZLIB=OFF \
            -DLLVM_ENABLE_LIBXML2=OFF \
            ../llvm/llvm/

      - name: Build Cling for Termux
        working-directory: build
        run: |
          ninja cling

      - name: Install
        working-directory: build
        run: |
          ninja install


      - name: Package
        run: |
          cd build/bin
          tar -cJf cling-termux-aarch64.tar.xz cling
          mv cling-termux-aarch64.tar.xz $GITHUB_WORKSPACE/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cling-termux-aarch64
          path: cling-termux-aarch64.tar.xz
